[package]
name = "gui_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.27"
gtk = "0.16.2"
regex = "1.7.1"
rusty-machine = "0.5.4"
